### ISSUE TITLE
create class Birthday

### ISSUE THREAD

**Issue by phase1912** [Yuriy-St/CoreMemo#28]
Need to create class Birthday with will be accept sting and convert it to datetime.
Also need to add date validation. If date not correct - need to show error message for user

**Comment by phase1912** [comment]
Need to complete this PR: https://github.com/Yuriy-St/CoreMemo/pull/30 to continue working with current ticket .
FYI @Yuriy-St

**Comment by Yuriy-St** [comment]
PR #30 has already been merged into the dev
